# Generated by Django 5.2.16 on 2026-07-19 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenantsecret_certificateaudit_digitalcertificate'),
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.CharField(choices=[('local', 'Local'), ('s3', 'S3'), ('minio', 'MinIO')], default='local', max_length=16)),
                ('bucket', models.CharField(blank=True, default='', max_length=128)),
                ('object_key', models.TextField()),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('encryption', models.CharField(default='envelope', max_length=32)),
                ('purpose', models.CharField(max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'purpose'], name='ops_storedf_tenant__d81830_idx')],
                'constraints': [models.UniqueConstraint(fields=('backend', 'bucket', 'object_key'), name='uq_stored_file_backend_bucket_key')],
            },
        ),
    ]
