# Generated by Django 5.2.16 on 2026-07-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_rls_app_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outboxmessage',
            options={'verbose_name': 'Mensagem outbox', 'verbose_name_plural': 'Mensagens outbox'},
        ),
        migrations.AlterModelOptions(
            name='storedfile',
            options={'verbose_name': 'Arquivo armazenado', 'verbose_name_plural': 'Arquivos armazenados'},
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('processed', 'Processado'), ('failed', 'Falhou'), ('dead', 'Morta')], default='pending', max_length=16),
        ),
    ]
