# Generated by Django 5.2.16 on 2026-07-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_field_verbose_names_pt'),
        ('ops', '0005_portuguese_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='aggregate_id',
            field=models.UUIDField(verbose_name='ID do agregado'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='aggregate_type',
            field=models.CharField(max_length=64, verbose_name='Tipo do agregado'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='available_at',
            field=models.DateTimeField(verbose_name='Disponível em'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='correlation_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID de correlação'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='event_type',
            field=models.CharField(max_length=128, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='Último erro'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='payload',
            field=models.JSONField(default=dict, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processado em'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('processed', 'Processado'), ('failed', 'Falhou'), ('dead', 'Morta')], default='pending', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='outboxmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='backend',
            field=models.CharField(choices=[('local', 'Local'), ('s3', 'S3'), ('minio', 'MinIO')], default='local', max_length=16, verbose_name='Backend'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='bucket',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Bucket'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='checksum_sha256',
            field=models.CharField(max_length=64, verbose_name='Checksum SHA-256'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Content-Type'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='encryption',
            field=models.CharField(default='envelope', max_length=32, verbose_name='Criptografia'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='object_key',
            field=models.TextField(verbose_name='Chave do objeto'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='purpose',
            field=models.CharField(max_length=64, verbose_name='Finalidade'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='size_bytes',
            field=models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
