# Generated by Django 5.2.16 on 2026-07-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenantsecret_certificateaudit_digitalcertificate'),
        ('ops', '0002_storedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcertificate',
            name='stored_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='ops.storedfile'),
        ),
        migrations.AddField(
            model_name='digitalcertificate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='certificateaudit',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='accounts.digitalcertificate'),
        ),
        migrations.AddField(
            model_name='tenantsecret',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secrets', to='accounts.tenant'),
        ),
        migrations.AddIndex(
            model_name='digitalcertificate',
            index=models.Index(fields=['tenant', 'status'], name='accounts_di_tenant__6beecd_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalcertificate',
            index=models.Index(fields=['tenant', 'not_after'], name='accounts_di_tenant__95997f_idx'),
        ),
        migrations.AddConstraint(
            model_name='digitalcertificate',
            constraint=models.UniqueConstraint(fields=('tenant', 'thumbprint_sha256'), name='uq_certificate_tenant_thumbprint'),
        ),
        migrations.AddConstraint(
            model_name='tenantsecret',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'key_name'), name='uq_tenant_secret_provider_key'),
        ),
    ]
