# Generated by Django 5.2.16 on 2026-07-19 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_digitalcertificate_stored_file_and_more'),
        ('master_data', '0002_servicecatalogitem_codigo_tributacao_nacional_iss'),
        ('ops', '0004_rls_app_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcertificate',
            name='cert_type',
            field=models.CharField(choices=[('a1', 'A1'), ('a3', 'A3')], default='a1', max_length=8),
        ),
        migrations.AddField(
            model_name='digitalcertificate',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digitalcertificate',
            name='key_usage',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='digitalcertificate',
            name='password_secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.tenantsecret'),
        ),
        migrations.AddField(
            model_name='digitalcertificate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='digitalcertificate',
            index=models.Index(fields=['tenant', 'cnpj', 'is_primary'], name='accounts_di_tenant__c83657_idx'),
        ),
        migrations.AddConstraint(
            model_name='digitalcertificate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant', 'cnpj'), name='uq_certificate_tenant_cnpj_primary'),
        ),
    ]
