# Generated by Django 5.2.16 on 2026-07-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_certificate_gates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateaudit',
            options={'verbose_name': 'Auditoria de certificado', 'verbose_name_plural': 'Auditorias de certificado'},
        ),
        migrations.AlterModelOptions(
            name='digitalcertificate',
            options={'verbose_name': 'Certificado digital', 'verbose_name_plural': 'Certificados digitais'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
        migrations.AlterModelOptions(
            name='tenantmembership',
            options={'verbose_name': 'Vínculo no tenant', 'verbose_name_plural': 'Vínculos no tenant'},
        ),
        migrations.AlterModelOptions(
            name='tenantrole',
            options={'verbose_name': 'Papel do tenant', 'verbose_name_plural': 'Papéis do tenant'},
        ),
        migrations.AlterModelOptions(
            name='tenantsecret',
            options={'verbose_name': 'Segredo do tenant', 'verbose_name_plural': 'Segredos do tenant'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('expiring', 'A expirar'), ('expired', 'Expirado'), ('revoked', 'Revogado')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('suspended', 'Suspenso'), ('provisioning', 'Provisionando')], default='active', max_length=32),
        ),
    ]
