# Generated by Django 5.2.16 on 2026-07-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_portuguese_verbose_names'),
        ('master_data', '0003_portuguese_verbose_names'),
        ('ops', '0005_portuguese_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcertificate',
            name='cert_type',
            field=models.CharField(choices=[('a1', 'A1'), ('a3', 'A3')], default='a1', max_length=8, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Principal'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='key_usage',
            field=models.JSONField(blank=True, default=list, verbose_name='Usos da chave'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='label',
            field=models.CharField(max_length=128, verbose_name='Rótulo'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='not_after',
            field=models.DateTimeField(verbose_name='Válido até'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='not_before',
            field=models.DateTimeField(verbose_name='Válido de'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='password_secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.tenantsecret', verbose_name='Segredo da senha'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='master_data.provider', verbose_name='Prestador'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('expiring', 'A expirar'), ('expired', 'Expirado'), ('revoked', 'Revogado')], default='active', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='stored_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='ops.storedfile', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='thumbprint_sha256',
            field=models.CharField(max_length=64, verbose_name='Thumbprint SHA-256'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='digitalcertificate',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='document',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='focus_layout',
            field=models.CharField(default='nfsen', max_length=16, verbose_name='Layout Focus'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(max_length=255, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configurações'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('suspended', 'Suspenso'), ('provisioning', 'Provisionando')], default='active', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='tenantsecret',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tenantsecret',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, verbose_name='Admin da plataforma'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último acesso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
