# Generated by Django 5.2.16 on 2026-07-20 01:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_field_verbose_names_pt'),
        ('master_data', '0004_field_verbose_names_pt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicProxy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('principal_cnpj', models.CharField(max_length=14, verbose_name='CNPJ outorgante')),
                ('proxy_document', models.CharField(max_length=14, verbose_name='Documento outorgado')),
                ('proxy_document_type', models.CharField(choices=[('cnpj', 'CNPJ'), ('cpf', 'CPF')], default='cnpj', max_length=4, verbose_name='Tipo documento outorgado')),
                ('ecac_service_codes', models.JSONField(blank=True, default=list, help_text='Ex.: ["PGDASD","GERARDAS12"]', verbose_name='Serviços e-CAC')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('expiring', 'A expirar'), ('expired', 'Expirada'), ('revoked', 'Revogada')], default='pending', max_length=16, verbose_name='Status')),
                ('valid_from', models.DateField(verbose_name='Válida de')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Válida até')),
                ('label', models.CharField(blank=True, default='', max_length=128, verbose_name='Rótulo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_proxies', to='master_data.provider', verbose_name='Prestador')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_proxies', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Procuração eletrônica',
                'verbose_name_plural': 'Procurações eletrônicas',
                'indexes': [models.Index(fields=['tenant', 'principal_cnpj', 'status'], name='accounts_el_tenant__a3051c_idx'), models.Index(fields=['tenant', 'valid_to'], name='accounts_el_tenant__612289_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active', 'expiring'])), fields=('tenant', 'principal_cnpj', 'proxy_document'), name='uq_electronic_proxy_active_pair')],
            },
        ),
    ]
