# Generated by Django 5.2.16 on 2026-08-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_electronic_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='focus_layout',
            field=models.CharField(default='nfsen', help_text='Preferência de layout NFS-e do tenant: nfsen = Nacional (emissor EXEQ/SEFIN no MVP); nfse = municipal (legado/lab). Não ativa a integração Focus.', max_length=16, verbose_name='Layout Exeq'),
        ),
    ]
