# Generated by Django 5.2.16 on 2026-08-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tenant_layout_exeq_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Flags do tenant. Ex.: {"nfe_enabled": true, "max_emit_cnpjs": 5, "payment_provider": "inter"}. max_emit_cnpjs limita Prestadores ativos no Hub/API até haver Plan formal.', verbose_name='Configurações'),
        ),
    ]
