# Generated by Django 5.2.16 on 2026-08-09 23:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tenant_settings_max_emit_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('limits', models.JSONField(blank=True, default=dict, help_text='Ex.: {"max_emit_cnpjs": 5, "max_users": 5, "max_nf_month": 500}. null / omitido em uma chave = sem teto para aquele entitlement.', verbose_name='Limites')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Flags do tenant. Ex.: {"nfe_enabled": true, "payment_provider": "inter"}. Limites comerciais preferem Subscription.plan.limits; max_emit_cnpjs em settings ainda funciona como override/fallback.', verbose_name='Configurações'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('trialing', 'Trial'), ('active', 'Ativo'), ('past_due', 'Inadimplente'), ('canceled', 'Cancelado')], default='active', max_length=16, verbose_name='Status')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Início do período')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim do período')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.plan', verbose_name='Plano')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
