# Generated by Django 5.2.16 on 2026-09-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_plan_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Flags do tenant (JSON avançado). Tipos de emissão: use Admin → checkboxes ou {"nfse_enabled": true, "nfe_enabled": true}. Ex.: payment_provider, max_emit_cnpjs. Limites comerciais preferem Subscription.plan.limits.', verbose_name='Configurações'),
        ),
    ]
