# Generated by Django 5.2.16 on 2026-07-19 17:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_digitalcertificate_stored_file_and_more'),
        ('issuance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('phone_e164', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('collecting', 'Collecting'), ('ready_to_confirm', 'Ready'), ('emitted', 'Emitted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='collecting', max_length=32)),
                ('draft_payload', models.JSONField(blank=True, default=dict)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nf_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_sessions', to='issuance.nfissue')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=64)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=128)),
                ('nf_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_notifications', to='issuance.nfissue')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='channel.channelsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='channelsession',
            index=models.Index(fields=['tenant', 'phone_e164', 'status'], name='channel_cha_tenant__663a9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelsession',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_channel_session_tenant_idempotency'),
        ),
    ]
