# Generated by Django 5.2.16 on 2026-07-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelnotification',
            options={'verbose_name': 'Notificação do canal', 'verbose_name_plural': 'Notificações do canal'},
        ),
        migrations.AlterModelOptions(
            name='channelsession',
            options={'verbose_name': 'Sessão do canal', 'verbose_name_plural': 'Sessões do canal'},
        ),
        migrations.AlterField(
            model_name='channelnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('failed', 'Falhou')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='status',
            field=models.CharField(choices=[('collecting', 'Coletando'), ('ready_to_confirm', 'Pronta para confirmar'), ('emitted', 'Emitida'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='collecting', max_length=32),
        ),
    ]
