# Generated by Django 5.2.16 on 2026-07-20 00:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_field_verbose_names_pt'),
        ('channel', '0002_portuguese_verbose_names'),
        ('issuance', '0004_field_verbose_names_pt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='channelnotification',
            name='event_type',
            field=models.CharField(max_length=64, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='channelnotification',
            name='message_body',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='channelnotification',
            name='phone_e164',
            field=models.CharField(max_length=20, verbose_name='Telefone (E.164)'),
        ),
        migrations.AlterField(
            model_name='channelnotification',
            name='provider_ref',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Referência do provedor'),
        ),
        migrations.AlterField(
            model_name='channelnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('failed', 'Falhou')], default='pending', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='channelnotification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='channelnotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='draft_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Rascunho'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='idempotency_key',
            field=models.CharField(max_length=128, verbose_name='Chave de idempotência'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='last_message_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última mensagem em'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='nf_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_sessions', to='issuance.nfissue', verbose_name='Emissão NFS-e'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='phone_e164',
            field=models.CharField(max_length=20, verbose_name='Telefone (E.164)'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='status',
            field=models.CharField(choices=[('collecting', 'Coletando'), ('ready_to_confirm', 'Pronta para confirmar'), ('emitted', 'Emitida'), ('expired', 'Expirada'), ('cancelled', 'Cancelada')], default='collecting', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='channelsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
