# Generated by Django 5.2.16 on 2026-07-19 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_tenant_roles'),
        ('issuance', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('amount_cents', models.BigIntegerField()),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('gateway_ref', models.CharField(blank=True, default='', max_length=128)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='master_data.customer')),
                ('nf_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='issuance.nfissue')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='asaas', max_length=32)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('signature', models.CharField(blank=True, default='', max_length=256)),
                ('signature_valid', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField()),
                ('paid_at', models.DateTimeField()),
                ('gateway_ref', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='billing.charge')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='accounts.tenant')),
                ('webhook_inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='billing.webhookinbox')),
            ],
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='billing_cha_tenant__ec49c0_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['tenant', 'gateway_ref'], name='billing_cha_tenant__5017f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_charge_tenant_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='ck_charge_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='webhookinbox',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'idempotency_key'), name='uq_webhook_inbox_tenant_provider_key'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['charge', 'paid_at'], name='billing_pay_charge__7296dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='ck_payment_event_amount_positive'),
        ),
    ]
