# Generated by Django 5.2.16 on 2026-07-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': 'Cobrança', 'verbose_name_plural': 'Cobranças'},
        ),
        migrations.AlterModelOptions(
            name='paymentevent',
            options={'verbose_name': 'Evento de pagamento', 'verbose_name_plural': 'Eventos de pagamento'},
        ),
        migrations.AlterModelOptions(
            name='webhookinbox',
            options={'verbose_name': 'Inbox de webhook', 'verbose_name_plural': 'Inboxes de webhook'},
        ),
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('registered', 'Registrada'), ('paid', 'Paga'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada'), ('failed', 'Falhou')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='status',
            field=models.CharField(choices=[('received', 'Recebido'), ('processing', 'Processando'), ('processed', 'Processado'), ('failed', 'Falhou')], default='received', max_length=16),
        ),
    ]
