# Generated by Django 5.2.16 on 2026-07-20 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_field_verbose_names_pt'),
        ('billing', '0002_portuguese_verbose_names'),
        ('issuance', '0004_field_verbose_names_pt'),
        ('master_data', '0004_field_verbose_names_pt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='amount_cents',
            field=models.BigIntegerField(verbose_name='Valor (centavos)'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='correlation_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='ID de correlação'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='master_data.customer', verbose_name='Tomador'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='due_date',
            field=models.DateField(verbose_name='Vencimento'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='gateway_ref',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Referência gateway'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='idempotency_key',
            field=models.CharField(max_length=128, verbose_name='Chave de idempotência'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='nf_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='issuance.nfissue', verbose_name='Emissão NFS-e'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('registered', 'Registrada'), ('paid', 'Paga'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada'), ('failed', 'Falhou')], default='pending', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
