# Generated by Django 5.2.16 on 2026-07-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_field_verbose_names_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Código de barras'),
        ),
        migrations.AddField(
            model_name='charge',
            name='billing_type',
            field=models.CharField(blank=True, default='BOLETO', max_length=32, verbose_name='Tipo de cobrança'),
        ),
        migrations.AddField(
            model_name='charge',
            name='boleto_pdf_url',
            field=models.URLField(blank=True, default='', max_length=512, verbose_name='URL PDF do boleto'),
        ),
        migrations.AddField(
            model_name='charge',
            name='digitable_line',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Linha digitável'),
        ),
        migrations.AddField(
            model_name='charge',
            name='gateway_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload do gateway'),
        ),
        migrations.AddField(
            model_name='charge',
            name='payment_url',
            field=models.URLField(blank=True, default='', max_length=512, verbose_name='URL do boleto'),
        ),
        migrations.AddField(
            model_name='charge',
            name='pix_copy_paste',
            field=models.TextField(blank=True, default='', verbose_name='PIX copia e cola'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='amount_cents',
            field=models.BigIntegerField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='amount_cents',
            field=models.BigIntegerField(verbose_name='Valor'),
        ),
    ]
