# Generated by Django 5.2.16 on 2026-07-20 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_electronic_proxy'),
        ('billing', '0004_charge_boleto_artifacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookinbox',
            options={'verbose_name': 'Caixa de entrada de webhook', 'verbose_name_plural': 'Caixas de entrada de webhook'},
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='billing.charge', verbose_name='Cobrança'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='gateway_ref',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Referência gateway'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='paid_at',
            field=models.DateTimeField(verbose_name='Pago em'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='webhook_inbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='billing.webhookinbox', verbose_name='Caixa de entrada de webhook'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Mensagem de erro'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='idempotency_key',
            field=models.CharField(max_length=128, verbose_name='Chave de idempotência'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='payload_hash',
            field=models.CharField(max_length=64, verbose_name='Hash do payload'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processado em'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='provider',
            field=models.CharField(choices=[('inter', 'Inter'), ('asaas', 'Asaas'), ('c6', 'C6')], default='inter', max_length=32, verbose_name='Provedor'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='raw_payload',
            field=models.JSONField(default=dict, verbose_name='Payload bruto'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Assinatura'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='signature_valid',
            field=models.BooleanField(default=False, verbose_name='Assinatura válida'),
        ),
        migrations.AlterField(
            model_name='webhookinbox',
            name='status',
            field=models.CharField(choices=[('received', 'Recebido'), ('processing', 'Processando'), ('processed', 'Processado'), ('failed', 'Falhou')], default='received', max_length=16, verbose_name='Status'),
        ),
    ]
