# Generated by Django 5.2.16 on 2026-07-21 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_electronic_proxy'),
        ('billing', '0005_webhook_paymentevent_verbose_names_pt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32, verbose_name='Provedor')),
                ('action', models.CharField(max_length=64, verbose_name='Ação')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_provider_audits', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Auditoria de provedor de cobrança',
                'verbose_name_plural': 'Auditorias de provedor de cobrança',
                'indexes': [models.Index(fields=['tenant', 'provider', 'created_at'], name='billing_pay_tenant__4b69a0_idx')],
            },
        ),
    ]
