# Generated by Django 5.2.16 on 2026-07-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_charge_pdf_file'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='charge',
            new_name='billing_cha_tenant__5c54cb_idx',
            old_name='billing_charge_sched_grp_idx',
        ),
        migrations.RenameIndex(
            model_name='charge',
            new_name='billing_cha_tenant__ba5b55_idx',
            old_name='billing_charge_seu_numero_idx',
        ),
    ]
