# Generated by Django 5.2.16 on 2026-08-10 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_plan_subscription'),
        ('master_data', '0007_nfe_greenfield_u2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('phone_e164', models.CharField(blank=True, default='', max_length=32, verbose_name='WhatsApp/telefone (E.164)')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('document', models.CharField(blank=True, default='', max_length=14, verbose_name='CPF/CNPJ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='Última compra')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Qtd. pedidos')),
                ('total_spent_cents', models.BigIntegerField(default=0, verbose_name='Receita acumulada (centavos)')),
                ('avg_ticket_cents', models.BigIntegerField(default=0, verbose_name='Ticket médio (centavos)')),
                ('fiscal_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_profiles', to='master_data.customer', verbose_name='Tomador fiscal (opcional)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Cliente Food',
                'verbose_name_plural': 'Clientes Food',
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('counter', 'Balcão'), ('other', 'Outro')], max_length=16, verbose_name='Canal')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_payment', 'Aguardando pagamento'), ('confirmed', 'Confirmado'), ('preparing', 'Em preparo'), ('ready', 'Pronto'), ('fulfilled', 'Entregue/concluído'), ('cancelled', 'Cancelado')], default='draft', max_length=32, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Não pago'), ('awaiting_pix', 'Pix pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Estornado')], default='unpaid', max_length=16, verbose_name='Status pagamento')),
                ('subtotal_cents', models.BigIntegerField(default=0, verbose_name='Subtotal')),
                ('discount_cents', models.BigIntegerField(default=0, verbose_name='Desconto')),
                ('total_cents', models.BigIntegerField(default=0, verbose_name='Total')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='Chave de idempotência')),
                ('pix_txid', models.CharField(blank=True, default='', max_length=128, verbose_name='Pix txid')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('channel_ref', models.CharField(blank=True, default='', max_length=128, verbose_name='Ref. canal (ex. message id)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='food.foodcustomer', verbose_name='Cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Pedido Food',
                'verbose_name_plural': 'Pedidos Food',
            },
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sku', models.CharField(max_length=64, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('category', models.CharField(blank=True, default='', max_length=128, verbose_name='Categoria')),
                ('unit', models.CharField(default='un', max_length=16, verbose_name='Unidade')),
                ('price_cents', models.BigIntegerField(default=0, verbose_name='Preço (centavos)')),
                ('cost_cents', models.BigIntegerField(default=0, verbose_name='Custo (centavos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Produto Food',
                'verbose_name_plural': 'Produtos Food',
            },
        ),
        migrations.CreateModel(
            name='FoodOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sku', models.CharField(max_length=64, verbose_name='SKU (snapshot)')),
                ('name', models.CharField(max_length=255, verbose_name='Nome (snapshot)')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('unit', models.CharField(default='un', max_length=16, verbose_name='Unidade')),
                ('unit_price_cents', models.BigIntegerField(verbose_name='Preço unitário')),
                ('line_total_cents', models.BigIntegerField(verbose_name='Total da linha')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='food.foodorder', verbose_name='Pedido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='food.foodproduct', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do pedido Food',
                'verbose_name_plural': 'Itens do pedido Food',
            },
        ),
        migrations.CreateModel(
            name='FoodStockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Saldo')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Mínimo (alerta)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balance', to='food.foodproduct', verbose_name='Produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Estoque Food',
                'verbose_name_plural': 'Estoques Food',
            },
        ),
        migrations.CreateModel(
            name='FoodStockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída'), ('adjust', 'Ajuste')], max_length=16, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantidade')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Saldo após')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Motivo')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='food.foodorder', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='food.foodproduct', verbose_name='Produto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Movimento de estoque Food',
                'verbose_name_plural': 'Movimentos de estoque Food',
            },
        ),
        migrations.AddIndex(
            model_name='foodcustomer',
            index=models.Index(fields=['tenant', 'is_active'], name='food_foodcu_tenant__fdcca7_idx'),
        ),
        migrations.AddIndex(
            model_name='foodcustomer',
            index=models.Index(fields=['tenant', 'last_order_at'], name='food_foodcu_tenant__95bc13_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodcustomer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_e164', ''), _negated=True), fields=('tenant', 'phone_e164'), name='uq_food_customer_tenant_phone'),
        ),
        migrations.AddConstraint(
            model_name='foodcustomer',
            constraint=models.CheckConstraint(condition=models.Q(('total_spent_cents__gte', 0), ('avg_ticket_cents__gte', 0)), name='ck_food_customer_money_nonneg'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['tenant', 'status'], name='food_foodor_tenant__9b0323_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['tenant', 'channel'], name='food_foodor_tenant__32287f_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['tenant', 'payment_status'], name='food_foodor_tenant__79cd3f_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['tenant', 'created_at'], name='food_foodor_tenant__8c953a_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_food_order_tenant_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='foodorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_cents__gte', 0), ('discount_cents__gte', 0), ('total_cents__gte', 0), ('discount_cents__lte', models.F('subtotal_cents'))), name='ck_food_order_money'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['tenant', 'is_active'], name='food_foodpr_tenant__058b48_idx'),
        ),
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['tenant', 'category'], name='food_foodpr_tenant__95168c_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodproduct',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='uq_food_product_tenant_sku'),
        ),
        migrations.AddConstraint(
            model_name='foodproduct',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents__gte', 0), ('cost_cents__gte', 0)), name='ck_food_product_money_nonneg'),
        ),
        migrations.AddIndex(
            model_name='foodorderline',
            index=models.Index(fields=['tenant', 'order'], name='food_foodor_tenant__e3cb69_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_price_cents__gte', 0), ('line_total_cents__gte', 0)), name='ck_food_order_line_values'),
        ),
        migrations.AddIndex(
            model_name='foodstockbalance',
            index=models.Index(fields=['tenant', 'quantity'], name='food_foodst_tenant__a12684_idx'),
        ),
        migrations.AddIndex(
            model_name='foodstockmovement',
            index=models.Index(fields=['tenant', 'product', 'created_at'], name='food_foodst_tenant__e538b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodstockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_food_stock_movement_qty_pos'),
        ),
    ]
