# Generated by Django 5.2.16 on 2026-08-10 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_plan_subscription'),
        ('billing', '0009_d12_cosmetic_index_verbose'),
        ('food', '0001_initial_exeq_hub_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to='billing.charge', verbose_name='Cobrança (Pix/boleto)'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['tenant', 'charge'], name='food_foodor_tenant__982efc_idx'),
        ),
    ]
