# Generated by Django 5.2.16 on 2026-08-10 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_plan_subscription'),
        ('channel', '0005_channel_nfe_invoice_rf72'),
        ('food', '0002_food_order_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.SlugField(max_length=64, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Início')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Campanha Food',
                'verbose_name_plural': 'Campanhas Food',
            },
        ),
        migrations.CreateModel(
            name='FoodCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=64, verbose_name='Código do cupom')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentual'), ('fixed_cents', 'Valor fixo')], max_length=16, verbose_name='Tipo de desconto')),
                ('percent_bps', models.PositiveIntegerField(default=0, help_text='1000 = 10%. Usado quando tipo=percent.', verbose_name='Percentual (basis points)')),
                ('amount_cents', models.BigIntegerField(default=0, verbose_name='Valor fixo (centavos)')),
                ('min_order_cents', models.BigIntegerField(default=0, verbose_name='Pedido mínimo')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máx. resgates (null=ilimitado)')),
                ('redemption_count', models.PositiveIntegerField(default=0, verbose_name='Resgates realizados')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='food.foodcampaign', verbose_name='Campanha')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Cupom Food',
                'verbose_name_plural': 'Cupons Food',
            },
        ),
        migrations.AddField(
            model_name='foodorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='food.foodcoupon', verbose_name='Cupom aplicado'),
        ),
        migrations.CreateModel(
            name='FoodCouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('discount_cents', models.BigIntegerField(verbose_name='Desconto aplicado')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='food.foodcampaign', verbose_name='Campanha')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='food.foodcoupon', verbose_name='Cupom')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='food.foodcustomer', verbose_name='Cliente')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemption', to='food.foodorder', verbose_name='Pedido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Resgate de cupom Food',
                'verbose_name_plural': 'Resgates de cupom Food',
            },
        ),
        migrations.CreateModel(
            name='FoodRetentionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('inactivity', 'Inatividade'), ('vip', 'VIP (frequência)'), ('high_ticket', 'Alto ticket'), ('custom', 'Custom')], max_length=32, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('inactivity_days', models.PositiveIntegerField(default=30, help_text='Usado em kind=inactivity (sem compra neste intervalo).', verbose_name='Dias de inatividade')),
                ('min_order_count', models.PositiveIntegerField(default=0, verbose_name='Mín. pedidos (VIP)')),
                ('min_avg_ticket_cents', models.BigIntegerField(default=0, verbose_name='Ticket médio mínimo (alto ticket)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Régua de retenção Food',
                'verbose_name_plural': 'Réguas de retenção Food',
            },
        ),
        migrations.CreateModel(
            name='FoodRetentionEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('stopped', 'Interrompida (comprou)')], default='active', max_length=16, verbose_name='Status')),
                ('next_sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Próxima etapa (sequence)')),
                ('enrolled_at', models.DateTimeField(verbose_name='Inscrito em')),
                ('next_fire_at', models.DateTimeField(verbose_name='Próximo disparo')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='Parado em')),
                ('stop_reason', models.CharField(blank=True, default='', max_length=64, verbose_name='Motivo parada')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_enrollments', to='food.foodcustomer', verbose_name='Cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='food.foodretentionrule', verbose_name='Régua')),
            ],
            options={
                'verbose_name': 'Inscrição régua Food',
                'verbose_name_plural': 'Inscrições régua Food',
            },
        ),
        migrations.CreateModel(
            name='FoodRetentionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Ordem')),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Na 1ª etapa: dias após elegibilidade/enroll.', verbose_name='Dias após etapa anterior')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=16, verbose_name='Canal')),
                ('message_template', models.TextField(help_text='Placeholders: {name}, {coupon_code}', verbose_name='Mensagem')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_steps', to='food.foodcoupon', verbose_name='Cupom (opcional)')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='food.foodretentionrule', verbose_name='Régua')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Etapa de régua Food',
                'verbose_name_plural': 'Etapas de régua Food',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='FoodRetentionDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('idempotency_key', models.CharField(max_length=160, verbose_name='Idempotência')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('skipped', 'Ignorado'), ('failed', 'Falhou')], max_length=16, verbose_name='Status')),
                ('message_body', models.TextField(blank=True, default='', verbose_name='Mensagem')),
                ('fired_at', models.DateTimeField(verbose_name='Disparado em')),
                ('channel_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_retention_dispatches', to='channel.channelnotification', verbose_name='Notificação canal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='food.foodretentionenrollment', verbose_name='Inscrição')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='food.foodretentionstep', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Disparo régua Food',
                'verbose_name_plural': 'Disparos régua Food',
            },
        ),
        migrations.AddConstraint(
            model_name='foodcampaign',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_food_campaign_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='foodcoupon',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_food_coupon_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='foodcoupon',
            constraint=models.CheckConstraint(condition=models.Q(('percent_bps__lte', 10000), ('amount_cents__gte', 0), ('min_order_cents__gte', 0)), name='ck_food_coupon_values'),
        ),
        migrations.AddConstraint(
            model_name='foodcouponredemption',
            constraint=models.CheckConstraint(condition=models.Q(('discount_cents__gte', 0)), name='ck_food_coupon_redemption_nonneg'),
        ),
        migrations.AddIndex(
            model_name='foodretentionrule',
            index=models.Index(fields=['tenant', 'is_active', 'kind'], name='food_foodre_tenant__2ca8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='foodretentionenrollment',
            index=models.Index(fields=['tenant', 'status', 'next_fire_at'], name='food_foodre_tenant__4f10c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodretentionenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant', 'rule', 'customer'), name='uq_food_retention_enrollment_active'),
        ),
        migrations.AddConstraint(
            model_name='foodretentionstep',
            constraint=models.UniqueConstraint(fields=('tenant', 'rule', 'sequence'), name='uq_food_retention_step_seq'),
        ),
        migrations.AddConstraint(
            model_name='foodretentiondispatch',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_food_retention_dispatch_idem'),
        ),
    ]
