# Generated by Django 5.2.16 on 2026-08-10 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_plan_subscription'),
        ('food', '0003_v11_retention_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='delivery_address',
            field=models.TextField(blank=True, default='', verbose_name='Endereço de entrega'),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='fulfillment_mode',
            field=models.CharField(choices=[('pickup', 'Retirada'), ('delivery', 'Delivery'), ('counter', 'Balcão')], default='pickup', max_length=16, verbose_name='Modo de atendimento'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('counter', 'Balcão'), ('ifood', 'iFood'), ('aiqfome', 'aiqfome'), ('other', 'Outro')], max_length=16, verbose_name='Canal'),
        ),
        migrations.CreateModel(
            name='FoodDeliveryRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('service_date', models.DateField(verbose_name='Data do serviço')),
                ('driver_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Motorista')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em rota'), ('closed', 'Fechada')], default='open', max_length=16, verbose_name='Status')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Rota de delivery Food',
                'verbose_name_plural': 'Rotas de delivery Food',
            },
        ),
        migrations.CreateModel(
            name='FoodDeliveryStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sequence', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('failed', 'Falha')], default='pending', max_length=20, verbose_name='Status')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notas')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_stop', to='food.foodorder', verbose_name='Pedido')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='food.fooddeliveryroute', verbose_name='Rota')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Parada delivery Food',
                'verbose_name_plural': 'Paradas delivery Food',
            },
        ),
        migrations.CreateModel(
            name='FoodMarketplaceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider', models.CharField(choices=[('ifood', 'iFood'), ('aiqfome', 'aiqfome')], max_length=16, verbose_name='Provedor')),
                ('merchant_ref', models.CharField(max_length=128, verbose_name='ID loja no marketplace')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Config')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Conexão marketplace Food',
                'verbose_name_plural': 'Conexões marketplace Food',
            },
        ),
        migrations.AddField(
            model_name='foodorder',
            name='marketplace_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='food.foodmarketplaceconnection', verbose_name='Conexão marketplace'),
        ),
        migrations.CreateModel(
            name='FoodPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ordered', 'Pedido ao fornecedor'), ('received', 'Recebido'), ('cancelled', 'Cancelado')], default='draft', max_length=16, verbose_name='Status')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='Idempotência')),
                ('expected_at', models.DateField(blank=True, null=True, verbose_name='Previsão')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Recebido em')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('total_cents', models.BigIntegerField(default=0, verbose_name='Total')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Compra Food',
                'verbose_name_plural': 'Compras Food',
            },
        ),
        migrations.CreateModel(
            name='FoodPurchaseLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Qtd')),
                ('unit_cost_cents', models.BigIntegerField(default=0, verbose_name='Custo unitário')),
                ('line_total_cents', models.BigIntegerField(default=0, verbose_name='Total linha')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='food.foodproduct', verbose_name='Produto')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='food.foodpurchase', verbose_name='Compra')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Item de compra Food',
                'verbose_name_plural': 'Itens de compra Food',
            },
        ),
        migrations.CreateModel(
            name='FoodSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('document', models.CharField(blank=True, default='', max_length=14, verbose_name='CNPJ/CPF')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Fornecedor Food',
                'verbose_name_plural': 'Fornecedores Food',
            },
        ),
        migrations.AddField(
            model_name='foodpurchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='food.foodsupplier', verbose_name='Fornecedor'),
        ),
        migrations.AddIndex(
            model_name='fooddeliveryroute',
            index=models.Index(fields=['tenant', 'service_date', 'status'], name='food_foodde_tenant__9aa518_idx'),
        ),
        migrations.AddIndex(
            model_name='fooddeliverystop',
            index=models.Index(fields=['tenant', 'route', 'status'], name='food_foodde_tenant__0a96e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='fooddeliverystop',
            constraint=models.UniqueConstraint(fields=('tenant', 'route', 'sequence'), name='uq_food_delivery_stop_seq'),
        ),
        migrations.AddConstraint(
            model_name='foodmarketplaceconnection',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'merchant_ref'), name='uq_food_marketplace_merchant'),
        ),
        migrations.AddConstraint(
            model_name='foodpurchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_cost_cents__gte', 0), ('line_total_cents__gte', 0)), name='ck_food_purchase_line_values'),
        ),
        migrations.AddIndex(
            model_name='foodsupplier',
            index=models.Index(fields=['tenant', 'is_active'], name='food_foodsu_tenant__f04838_idx'),
        ),
        migrations.AddIndex(
            model_name='foodpurchase',
            index=models.Index(fields=['tenant', 'status'], name='food_foodpu_tenant__9f2a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='foodpurchase',
            index=models.Index(fields=['tenant', 'supplier'], name='food_foodpu_tenant__17c3ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodpurchase',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_food_purchase_tenant_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='foodpurchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents__gte', 0)), name='ck_food_purchase_total_nonneg'),
        ),
    ]
