# Generated by Django 5.2.16 on 2026-08-10 02:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_plan_subscription'),
        ('food', '0004_phase2_ops'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('expected_yield_bps', models.PositiveIntegerField(default=10000, help_text='10000 = 100%', verbose_name='Rendimento esperado (bps)')),
            ],
            options={
                'verbose_name': 'Ficha técnica Food',
                'verbose_name_plural': 'Fichas técnicas Food',
            },
        ),
        migrations.CreateModel(
            name='FoodBomComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Qtd por unidade do acabado')),
                ('scrap_bps', models.PositiveIntegerField(default=0, help_text='Extra sobre o consumo. 500 = 5%.', verbose_name='Perda planejada (bps)')),
            ],
            options={
                'verbose_name': 'Componente BOM Food',
                'verbose_name_plural': 'Componentes BOM Food',
            },
        ),
        migrations.CreateModel(
            name='FoodCapacitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('service_date', models.DateField(verbose_name='Data')),
                ('starts_at', models.TimeField(verbose_name='Início')),
                ('ends_at', models.TimeField(verbose_name='Fim')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Nome')),
                ('capacity_units', models.PositiveIntegerField(default=1, verbose_name='Capacidade (unidades)')),
                ('booked_units', models.PositiveIntegerField(default=0, verbose_name='Reservado')),
            ],
            options={
                'verbose_name': 'Slot capacidade Food',
                'verbose_name_plural': 'Slots capacidade Food',
            },
        ),
        migrations.CreateModel(
            name='FoodProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('in_progress', 'Em produção'), ('done', 'Concluída'), ('cancelled', 'Cancelada')], default='planned', max_length=16, verbose_name='Status')),
                ('quantity_planned', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Qtd planejada')),
                ('quantity_produced', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Qtd produzida')),
                ('loss_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Perda')),
                ('yield_bps', models.PositiveIntegerField(default=10000, verbose_name='Rendimento real (bps)')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='Idempotência')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
            ],
            options={
                'verbose_name': 'Ordem de produção Food',
                'verbose_name_plural': 'Ordens de produção Food',
            },
        ),
        migrations.AddField(
            model_name='foodstockbalance',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Reservado'),
        ),
        migrations.AlterField(
            model_name='foodstockbalance',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Saldo físico'),
        ),
        migrations.AddConstraint(
            model_name='foodstockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0), ('reserved_quantity__gte', 0)), name='ck_food_stock_nonneg'),
        ),
        migrations.AddField(
            model_name='foodbom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='food.foodproduct', verbose_name='Produto acabado'),
        ),
        migrations.AddField(
            model_name='foodbom',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='foodbomcomponent',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='food.foodbom', verbose_name='BOM'),
        ),
        migrations.AddField(
            model_name='foodbomcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_usages', to='food.foodproduct', verbose_name='Insumo'),
        ),
        migrations.AddField(
            model_name='foodbomcomponent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='foodcapacityslot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='foodproductionorder',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='food.foodbom', verbose_name='Ficha técnica'),
        ),
        migrations.AddField(
            model_name='foodproductionorder',
            name='capacity_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='food.foodcapacityslot', verbose_name='Slot'),
        ),
        migrations.AddField(
            model_name='foodproductionorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='food.foodproduct', verbose_name='Produto acabado'),
        ),
        migrations.AddField(
            model_name='foodproductionorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='foodbom',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'product'), name='uq_food_bom_active_product'),
        ),
        migrations.AddConstraint(
            model_name='foodbom',
            constraint=models.CheckConstraint(condition=models.Q(('expected_yield_bps__gte', 1), ('expected_yield_bps__lte', 10000)), name='ck_food_bom_yield_bps'),
        ),
        migrations.AddConstraint(
            model_name='foodbomcomponent',
            constraint=models.UniqueConstraint(fields=('tenant', 'bom', 'product'), name='uq_food_bom_component'),
        ),
        migrations.AddConstraint(
            model_name='foodbomcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_per_unit__gt', 0), ('scrap_bps__lte', 5000)), name='ck_food_bom_component_qty'),
        ),
        migrations.AddIndex(
            model_name='foodcapacityslot',
            index=models.Index(fields=['tenant', 'service_date'], name='food_foodca_tenant__d3d2e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodcapacityslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at')), ('booked_units__lte', models.F('capacity_units'))), name='ck_food_capacity_slot'),
        ),
        migrations.AddIndex(
            model_name='foodproductionorder',
            index=models.Index(fields=['tenant', 'status'], name='food_foodpr_tenant__94aef1_idx'),
        ),
        migrations.AddIndex(
            model_name='foodproductionorder',
            index=models.Index(fields=['tenant', 'product'], name='food_foodpr_tenant__b86377_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodproductionorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_food_production_order_idem'),
        ),
        migrations.AddConstraint(
            model_name='foodproductionorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_planned__gt', 0), ('quantity_produced__gte', 0), ('loss_quantity__gte', 0), ('yield_bps__lte', 10000)), name='ck_food_production_qty'),
        ),
    ]
