# Generated by Django 5.2.16 on 2026-08-14 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_plan_subscription'),
        ('billing', '0009_d12_cosmetic_index_verbose'),
        ('food', '0005_phase3_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmarketplaceconnection',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='access_token, base_url, orders_path, sku_map, stub_orders, http_mode', verbose_name='Config'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Não pago'), ('awaiting_pix', 'Pix pendente'), ('awaiting_payment', 'Pagamento pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Estornado')], default='unpaid', max_length=16, verbose_name='Status pagamento'),
        ),
        migrations.CreateModel(
            name='FoodPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider', models.CharField(choices=[('inter', 'Inter'), ('asaas', 'Asaas'), ('c6', 'C6'), ('mercadopago', 'Mercado Pago')], max_length=32, verbose_name='Provedor')),
                ('method', models.CharField(choices=[('pix', 'Pix'), ('card', 'Cartão')], max_length=16, verbose_name='Meio')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting_payment', 'Aguardando pagamento'), ('paid', 'Pago'), ('failed', 'Falhou'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='pending', max_length=24, verbose_name='Status')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='Chave de idempotência')),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=128, verbose_name='ID pagamento no provedor')),
                ('amount_cents', models.BigIntegerField(verbose_name='Valor (centavos)')),
                ('pix_copy_paste', models.TextField(blank=True, default='', verbose_name='PIX copia e cola')),
                ('failure_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Código de falha')),
                ('failure_detail', models.CharField(blank=True, default='', max_length=255, verbose_name='Detalhe da falha')),
                ('gateway_payload', models.JSONField(blank=True, null=True, verbose_name='Payload do gateway')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_payments', to='billing.charge', verbose_name='Cobrança billing (Inter)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='food.foodorder', verbose_name='Pedido')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Pagamento Food',
                'verbose_name_plural': 'Pagamentos Food',
            },
        ),
        migrations.CreateModel(
            name='FoodPaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('provider', models.CharField(max_length=32, verbose_name='Provedor')),
                ('event_id', models.CharField(max_length=128, verbose_name='ID do evento')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='food.foodpayment', verbose_name='Pagamento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Evento pagamento Food',
                'verbose_name_plural': 'Eventos pagamento Food',
            },
        ),
        migrations.AddIndex(
            model_name='foodpayment',
            index=models.Index(fields=['tenant', 'order', 'status'], name='food_foodpa_tenant__4697bf_idx'),
        ),
        migrations.AddIndex(
            model_name='foodpayment',
            index=models.Index(fields=['tenant', 'provider_payment_id'], name='food_foodpa_tenant__439100_idx'),
        ),
        migrations.AddIndex(
            model_name='foodpayment',
            index=models.Index(fields=['tenant', 'provider', 'status'], name='food_foodpa_tenant__81f738_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodpayment',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_food_payment_tenant_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='foodpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='ck_food_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='foodpaymentevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'event_id'), name='uq_food_payment_event_tenant_provider_event'),
        ),
    ]
