# Generated by Django 5.2.16 on 2026-07-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_servicecatalogitem_codigo_tributacao_nacional_iss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Tomador', 'verbose_name_plural': 'Tomadores'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Prestador', 'verbose_name_plural': 'Prestadores'},
        ),
        migrations.AlterModelOptions(
            name='servicecatalogitem',
            options={'verbose_name': 'Serviço do catálogo', 'verbose_name_plural': 'Serviços do catálogo'},
        ),
    ]
