# Generated by Django 5.2.16 on 2026-07-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_field_verbose_names_pt'),
        ('master_data', '0003_portuguese_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.JSONField(blank=True, default=dict, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.CharField(max_length=14, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=4, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.JSONField(blank=True, default=dict, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='document',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='legal_name',
            field=models.CharField(max_length=255, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='municipal_registration',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Inscrição municipal'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='tax_regime',
            field=models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=32, verbose_name='Regime tributário'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='trade_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='codigo_tributacao_nacional_iss',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Código tributação nacional ISS'),
        ),
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='lc116_item',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Item LC 116'),
        ),
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='service_code',
            field=models.CharField(max_length=32, verbose_name='Código do serviço'),
        ),
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
