# Generated by Django 5.2.16 on 2026-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_field_verbose_names_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cnae_principal',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CNAE principal'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contato_nome',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do contato'),
        ),
        migrations.AddField(
            model_name='customer',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de abertura'),
        ),
        migrations.AddField(
            model_name='customer',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('receita_federal', 'Receita Federal')], default='manual', max_length=32, verbose_name='Origem dos dados'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_lookup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última consulta cadastral'),
        ),
        migrations.AddField(
            model_name='customer',
            name='natureza_juridica',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Natureza jurídica'),
        ),
        migrations.AddField(
            model_name='customer',
            name='porte',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Porte'),
        ),
        migrations.AddField(
            model_name='customer',
            name='receita_raw_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload bruto Receita'),
        ),
        migrations.AddField(
            model_name='customer',
            name='situacao_cadastral',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Situação cadastral'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='provider',
            name='cnae_principal',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CNAE principal'),
        ),
        migrations.AddField(
            model_name='provider',
            name='contato_nome',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do contato'),
        ),
        migrations.AddField(
            model_name='provider',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de abertura'),
        ),
        migrations.AddField(
            model_name='provider',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('receita_federal', 'Receita Federal')], default='manual', max_length=32, verbose_name='Origem dos dados'),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_lookup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última consulta cadastral'),
        ),
        migrations.AddField(
            model_name='provider',
            name='natureza_juridica',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Natureza jurídica'),
        ),
        migrations.AddField(
            model_name='provider',
            name='porte',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Porte'),
        ),
        migrations.AddField(
            model_name='provider',
            name='receita_raw_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload bruto Receita'),
        ),
        migrations.AddField(
            model_name='provider',
            name='situacao_cadastral',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Situação cadastral'),
        ),
        migrations.AddField(
            model_name='provider',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='WhatsApp'),
        ),
    ]
