# Generated by Django 5.2.16 on 2026-07-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_cadastral_lookup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalServiceCatalogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=64, unique=True, verbose_name='Rótulo da versão')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Arquivo origem')),
                ('sheet_name', models.CharField(blank=True, default='LISTA.SERV.NAC.', max_length=64, verbose_name='Aba')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('superseded', 'Substituída')], default='draft', max_length=16, verbose_name='Status')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Qtd. códigos')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
            ],
            options={
                'verbose_name': 'Versão Lista Serviço Nacional',
                'verbose_name_plural': 'Versões Lista Serviço Nacional',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='NationalServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, verbose_name='Código tributação nacional')),
                ('item', models.PositiveSmallIntegerField(verbose_name='Item LC 116')),
                ('subitem', models.PositiveSmallIntegerField(verbose_name='Subitem')),
                ('desdobro', models.PositiveSmallIntegerField(default=0, verbose_name='Desdobro nacional')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('lc116_hint', models.CharField(blank=True, default='', max_length=16, verbose_name='Sugestão LC 116')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='master_data.nationalservicecatalogversion', verbose_name='Versão')),
            ],
            options={
                'verbose_name': 'Código Serviço Nacional',
                'verbose_name_plural': 'Códigos Serviço Nacional',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='idx_national_service_codigo')],
                'constraints': [models.UniqueConstraint(fields=('version', 'codigo'), name='uq_national_service_version_codigo')],
            },
        ),
    ]
