# Generated by Django 5.2.16 on 2026-08-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_national_service_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='state_registration',
            field=models.CharField(blank=True, default='', help_text='Obrigatória para emissão real NF-e (SEFAZ); opcional em stub.', max_length=32, verbose_name='Inscrição estadual (IE)'),
        ),
    ]
