# Generated by Django 5.2.16 on 2026-09-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_cadastral_cnaes_secundarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='NbsCatalogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=64, unique=True, verbose_name='Rótulo da versão')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Arquivo origem')),
                ('sheet_name', models.CharField(blank=True, default='LISTA.NBS_v2.0', max_length=64, verbose_name='Aba')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('superseded', 'Substituída')], default='draft', max_length=16, verbose_name='Status')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Qtd. códigos')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
            ],
            options={
                'verbose_name': 'Versão catálogo NBS',
                'verbose_name_plural': 'Versões catálogo NBS',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='codigo_nbs',
            field=models.CharField(blank=True, default='', help_text='Nomenclatura Brasileira de Serviços (9 dígitos, sem pontuação).', max_length=9, verbose_name='Código NBS'),
        ),
        migrations.CreateModel(
            name='NbsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=9, verbose_name='Código NBS')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='master_data.nbscatalogversion', verbose_name='Versão')),
            ],
            options={
                'verbose_name': 'Código NBS',
                'verbose_name_plural': 'Códigos NBS',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='servicecatalogitem',
            name='nbs_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_catalog_items', to='master_data.nbsitem', verbose_name='Item NBS (catálogo)'),
        ),
        migrations.AddIndex(
            model_name='nbsitem',
            index=models.Index(fields=['codigo'], name='idx_nbs_codigo'),
        ),
        migrations.AddConstraint(
            model_name='nbsitem',
            constraint=models.UniqueConstraint(fields=('version', 'codigo'), name='uq_nbs_version_codigo'),
        ),
    ]
