# Generated by Django 5.2.16 on 2026-09-05 01:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_plan_subscription'),
        ('master_data', '0010_nbs_catalog'),
        ('nfe', '0005_nfe_transmission_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfceInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='Chave de idempotência')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitting', 'Enviando'), ('polling', 'Consultando'), ('authorized', 'Autorizada'), ('rejected', 'Rejeitada'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='draft', max_length=32, verbose_name='Status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão otimista')),
                ('nature_operation', models.CharField(default='VENDA', max_length=60, verbose_name='Natureza da operação')),
                ('series', models.PositiveIntegerField(default=1, verbose_name='Série')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('tp_amb', models.CharField(default='2', max_length=1, verbose_name='Ambiente')),
                ('issue_date', models.DateField(verbose_name='Data de emissão')),
                ('payment_method', models.CharField(default='99', max_length=2, verbose_name='Forma pag. tPag')),
                ('payment_amount_cents', models.BigIntegerField(blank=True, null=True, verbose_name='Valor pag.')),
                ('discount_cents', models.BigIntegerField(default=0, verbose_name='Desconto (centavos)')),
                ('total_cents', models.BigIntegerField(default=0, verbose_name='Total (centavos)')),
                ('identification_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Identificação consumidor (transitória)')),
                ('omit_dest', models.BooleanField(default=True, verbose_name='Omitir dest no XML')),
                ('fiscal_snapshot', models.JSONField(blank=True, null=True, verbose_name='Snapshot fiscal')),
                ('taxes_summary', models.JSONField(blank=True, null=True, verbose_name='Totais impostos')),
                ('access_key', models.CharField(blank=True, default='', max_length=44, verbose_name='Chave')),
                ('protocol', models.CharField(blank=True, default='', max_length=64, verbose_name='Protocolo')),
                ('rejection_code', models.CharField(blank=True, default='', max_length=16, verbose_name='cStat')),
                ('rejection_message', models.CharField(blank=True, default='', max_length=512, verbose_name='Motivo rejeição')),
                ('number_consumed', models.BooleanField(default=False, verbose_name='Número consumido')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, verbose_name='Correlação')),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash')),
                ('last_validation', models.JSONField(blank=True, null=True, verbose_name='Última validação')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_invoices', to='master_data.provider', verbose_name='Emitente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'NFC-e',
                'verbose_name_plural': 'NFC-e',
            },
        ),
        migrations.CreateModel(
            name='NfceInvoiceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('actor', models.CharField(default='system', max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nfce.nfceinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_invoice_events', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Evento NFC-e',
                'verbose_name_plural': 'Eventos NFC-e',
                'ordering': ('occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='NfceInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(verbose_name='Item')),
                ('code', models.CharField(max_length=60, verbose_name='Código')),
                ('description', models.CharField(max_length=120, verbose_name='Descrição')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('cfop', models.CharField(max_length=4, verbose_name='CFOP')),
                ('unit', models.CharField(default='UN', max_length=6, verbose_name='Unidade')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantidade')),
                ('unit_price_cents', models.BigIntegerField(verbose_name='V. unitário (centavos)')),
                ('discount_cents', models.BigIntegerField(default=0, verbose_name='Desconto (centavos)')),
                ('total_cents', models.BigIntegerField(verbose_name='Total item (centavos)')),
                ('origin', models.CharField(default='0', max_length=1, verbose_name='Origem')),
                ('csosn', models.CharField(blank=True, default='', max_length=3, verbose_name='CSOSN')),
                ('icms_cst', models.CharField(blank=True, default='', max_length=3, verbose_name='CST ICMS')),
                ('taxes', models.JSONField(blank=True, default=dict, verbose_name='Impostos item')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nfce.nfceinvoice', verbose_name='NFC-e')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nfe.nfeproduct', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item NFC-e',
                'verbose_name_plural': 'Itens NFC-e',
                'ordering': ('line_number',),
            },
        ),
        migrations.CreateModel(
            name='NfceNumberSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('series', models.PositiveIntegerField(default=1, verbose_name='Série')),
                ('tp_amb', models.CharField(choices=[('2', 'Homologação'), ('1', 'Produção')], default='2', max_length=1, verbose_name='Ambiente')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Próximo número')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_number_series', to='master_data.provider', verbose_name='Emitente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Série NFC-e',
                'verbose_name_plural': 'Séries NFC-e',
            },
        ),
        migrations.CreateModel(
            name='TenantCscToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tp_amb', models.CharField(default='2', max_length=1, verbose_name='Ambiente')),
                ('csc_id', models.CharField(max_length=6, verbose_name='Id CSC')),
                ('csc_token', models.CharField(max_length=64, verbose_name='Token CSC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_csc_tokens', to='master_data.provider', verbose_name='Emitente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'CSC NFC-e',
                'verbose_name_plural': 'CSC NFC-e',
            },
        ),
        migrations.AddIndex(
            model_name='nfceinvoice',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='nfce_nfcein_tenant__b90844_idx'),
        ),
        migrations.AddIndex(
            model_name='nfceinvoice',
            index=models.Index(fields=['tenant', 'access_key'], name='nfce_nfcein_tenant__4163fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfceinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_nfce_invoice_tenant_idempotency'),
        ),
        migrations.AddIndex(
            model_name='nfceinvoiceevent',
            index=models.Index(fields=['invoice', 'occurred_at'], name='nfce_nfcein_invoice_418f5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfceinvoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_number'), name='uq_nfce_item_invoice_line'),
        ),
        migrations.AddConstraint(
            model_name='nfcenumberseries',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'series', 'tp_amb'), name='uq_nfce_series_provider_serie_amb'),
        ),
        migrations.AddConstraint(
            model_name='tenantcsctoken',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'tp_amb', 'csc_id'), name='uq_nfce_csc_tenant_provider_amb_id'),
        ),
    ]
