# Generated by Django 5.2.16 on 2026-09-05 02:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_plan_subscription'),
        ('nfce', '0001_nfce_greenfield'),
        ('ops', '0007_rls_nf_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('kind', models.CharField(choices=[('xml_authorized', 'XML autorizado'), ('danfe_pdf', 'DANFE NFC-e PDF')], max_length=32, verbose_name='Tipo')),
                ('checksum_sha256', models.CharField(max_length=64, verbose_name='Checksum SHA-256')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='nfce.nfceinvoice', verbose_name='NFC-e')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_artifacts', to='ops.storedfile', verbose_name='Arquivo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Artefato NFC-e',
                'verbose_name_plural': 'Artefatos NFC-e',
                'constraints': [models.UniqueConstraint(fields=('invoice', 'kind'), name='uq_nfce_artifact_invoice_kind')],
            },
        ),
    ]
