# Generated by Django 5.2.16 on 2026-07-19 17:19

import apps.fiscal.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_tenant_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('tax_regime', models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=32)),
                ('iss_retention_policy', models.CharField(default='by_rule', max_length=32)),
                ('status', models.CharField(default='active', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRuleCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('publish_checklist', models.JSONField(default=apps.fiscal.models.default_publish_checklist)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalTaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ibge_code', models.CharField(max_length=7)),
                ('municipio_nome', models.CharField(max_length=128)),
                ('uf', models.CharField(max_length=2)),
                ('service_code', models.CharField(max_length=32)),
                ('tax_regime', models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=32)),
                ('iss_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('irrf_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('pis_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('cofins_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('iss_retained', models.BooleanField(default=False)),
                ('simples_codigo_tributacao', models.SmallIntegerField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('focus_field_overrides', models.JSONField(blank=True, default=dict)),
                ('fiscal_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='fiscal.fiscalprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='fiscal.taxrulecatalog')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fiscalprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uq_fiscal_profile_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='taxrulecatalog',
            constraint=models.UniqueConstraint(fields=('tenant', 'version'), name='uq_tax_catalog_tenant_version'),
        ),
        migrations.AddConstraint(
            model_name='taxrulecatalog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('tenant',), name='uq_tax_catalog_one_published'),
        ),
        migrations.AddIndex(
            model_name='municipaltaxrule',
            index=models.Index(fields=['tenant', 'ibge_code', 'service_code', 'tax_regime', 'priority'], name='idx_tax_rule_resolve'),
        ),
        migrations.AddConstraint(
            model_name='municipaltaxrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'catalog', 'fiscal_profile', 'ibge_code', 'service_code', 'tax_regime', 'valid_from'), name='uq_municipal_tax_rule_natural_key'),
        ),
    ]
