# Generated by Django 5.2.16 on 2026-07-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalprofile',
            options={'verbose_name': 'Perfil fiscal', 'verbose_name_plural': 'Perfis fiscais'},
        ),
        migrations.AlterModelOptions(
            name='municipaltaxrule',
            options={'verbose_name': 'Regra municipal', 'verbose_name_plural': 'Regras municipais'},
        ),
        migrations.AlterModelOptions(
            name='taxrulecatalog',
            options={'verbose_name': 'Catálogo de regras', 'verbose_name_plural': 'Catálogos de regras'},
        ),
        migrations.AlterField(
            model_name='taxrulecatalog',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('superseded', 'Substituído')], default='draft', max_length=16),
        ),
    ]
