# Generated by Django 5.2.16 on 2026-07-20 00:36

import apps.fiscal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_field_verbose_names_pt'),
        ('fiscal', '0002_portuguese_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='fiscalprofile',
            name='iss_retention_policy',
            field=models.CharField(default='by_rule', max_length=32, verbose_name='Política retenção ISS'),
        ),
        migrations.AlterField(
            model_name='fiscalprofile',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='fiscalprofile',
            name='status',
            field=models.CharField(default='active', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fiscalprofile',
            name='tax_regime',
            field=models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=32, verbose_name='Regime tributário'),
        ),
        migrations.AlterField(
            model_name='fiscalprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='fiscalprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='taxrulecatalog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='taxrulecatalog',
            name='publish_checklist',
            field=models.JSONField(default=apps.fiscal.models.default_publish_checklist, verbose_name='Checklist de publicação'),
        ),
        migrations.AlterField(
            model_name='taxrulecatalog',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publicado em'),
        ),
        migrations.AlterField(
            model_name='taxrulecatalog',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('superseded', 'Substituído')], default='draft', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='taxrulecatalog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='taxrulecatalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='taxrulecatalog',
            name='version',
            field=models.PositiveIntegerField(verbose_name='Versão'),
        ),
    ]
