# Generated by Django 5.2.16 on 2026-07-20 00:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_field_verbose_names_pt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='fiscal.taxrulecatalog', verbose_name='Catálogo'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='cofins_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='Alíquota COFINS'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='fiscal_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='fiscal.fiscalprofile', verbose_name='Perfil fiscal'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='focus_field_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='Overrides Focus'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='ibge_code',
            field=models.CharField(max_length=7, verbose_name='Código IBGE'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='irrf_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='Alíquota IRRF'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='iss_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='Alíquota ISS'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='iss_retained',
            field=models.BooleanField(default=False, verbose_name='ISS retido'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='municipio_nome',
            field=models.CharField(max_length=128, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='pis_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='Alíquota PIS'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='service_code',
            field=models.CharField(max_length=32, verbose_name='Código do serviço'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='simples_codigo_tributacao',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Código tributação SN'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='tax_regime',
            field=models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=32, verbose_name='Regime tributário'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='valid_from',
            field=models.DateField(verbose_name='Válido de'),
        ),
        migrations.AlterField(
            model_name='municipaltaxrule',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Válido até'),
        ),
    ]
