# Generated by Django 5.2.16 on 2026-07-27 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_municipal_rule_verbose_pt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RtcNormativeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=64, unique=True, verbose_name='Rótulo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('superseded', 'Substituído')], default='draft', max_length=16, verbose_name='Status')),
                ('nt_refs', models.CharField(blank=True, default='', help_text='Ex.: SE/CGNFS-e NT 009; LC 214/2025; ADCT art. 125', max_length=255, verbose_name='Referências NT')),
                ('changelog', models.TextField(blank=True, default='', verbose_name='Changelog')),
                ('owner', models.CharField(blank=True, default='', max_length=128, verbose_name='Responsável conformidade')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Versão normativa RTC',
                'verbose_name_plural': 'Versões normativas RTC',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RtcClassificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cst', 'CST IBS/CBS'), ('c_class_trib', 'cClassTrib'), ('c_ind_op', 'cIndOp')], max_length=16, verbose_name='Tipo')),
                ('code', models.CharField(max_length=16, verbose_name='Código')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('requires_group', models.CharField(blank=True, default='', help_text='Ex.: gIBSCBS, gIBSCBSMono, vazio se não aplicável', max_length=32, verbose_name='Grupo XML exigido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='fiscal.rtcnormativeversion', verbose_name='Versão normativa')),
            ],
            options={
                'verbose_name': 'Código classificação RTC',
                'verbose_name_plural': 'Códigos classificação RTC',
                'ordering': ['kind', 'code'],
                'indexes': [models.Index(fields=['kind', 'code'], name='idx_rtc_class_kind_code')],
                'constraints': [models.UniqueConstraint(fields=('version', 'kind', 'code'), name='uq_rtc_classification_version_kind_code')],
            },
        ),
    ]
