# Generated by Django 5.2.16 on 2026-09-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_municipalrule_c_trib_mun'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCatalogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=64, unique=True, verbose_name='Rótulo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('superseded', 'Substituída')], default='draft', max_length=16, verbose_name='Status')),
                ('source_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash origem')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Qtd. itens')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
            ],
            options={
                'verbose_name': 'Versão catálogo mercadorias',
                'verbose_name_plural': 'Versões catálogo mercadorias',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ncm', 'NCM'), ('cfop', 'CFOP'), ('unit', 'Unidade'), ('cest', 'CEST')], max_length=8, verbose_name='Tipo')),
                ('code', models.CharField(max_length=16, verbose_name='Código')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fiscal.goodscatalogversion', verbose_name='Versão')),
            ],
            options={
                'verbose_name': 'Item catálogo mercadorias',
                'verbose_name_plural': 'Itens catálogo mercadorias',
                'ordering': ['kind', 'code'],
                'indexes': [models.Index(fields=['kind', 'code'], name='idx_goods_catalog_kind_code')],
                'constraints': [models.UniqueConstraint(fields=('version', 'kind', 'code'), name='uq_goods_catalog_version_kind_code')],
            },
        ),
    ]
