# Generated by Django 5.2.16 on 2026-07-29 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_electronic_proxy'),
        ('master_data', '0006_national_service_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('requires_deposit', models.BooleanField(default=False, verbose_name='Exige sinal')),
                ('manual_booking_only', models.BooleanField(default=False, verbose_name='Somente agendamento manual')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_restriction', to='master_data.customer', verbose_name='Cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Restrição de cliente',
                'verbose_name_plural': 'Restrições de cliente',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64, verbose_name='Fuso horário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professionals', to='master_data.provider', verbose_name='Prestador')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduling_professionals', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='CalendarBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('starts_at', models.DateTimeField(verbose_name='Início')),
                ('ends_at', models.DateTimeField(verbose_name='Fim')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Motivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduling_calendar_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_blocks', to='scheduling.professional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Bloqueio de agenda',
                'verbose_name_plural': 'Bloqueios de agenda',
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='Dia da semana')),
                ('starts_at', models.TimeField(verbose_name='Início')),
                ('ends_at', models.TimeField(verbose_name='Fim')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='scheduling.professional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Horário comercial',
                'verbose_name_plural': 'Horários comerciais',
            },
        ),
        migrations.CreateModel(
            name='RecurringTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('weekday', models.PositiveSmallIntegerField(verbose_name='Dia da semana')),
                ('starts_at', models.TimeField(verbose_name='Início')),
                ('ends_at', models.TimeField(verbose_name='Fim')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_time_offs', to='scheduling.professional', verbose_name='Profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Folga recorrente',
                'verbose_name_plural': 'Folgas recorrentes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duração (min)')),
                ('price_cents', models.BigIntegerField(default=0, verbose_name='Preço')),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0, verbose_name='Buffer antes (min)')),
                ('buffer_after_minutes', models.PositiveIntegerField(default=0, verbose_name='Buffer depois (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduling_services', to='master_data.servicecatalogitem', verbose_name='Item do catálogo fiscal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Serviço (agenda)',
                'verbose_name_plural': 'Serviços (agenda)',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_services', to='scheduling.professional', verbose_name='Profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_services', to='scheduling.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Profissional × serviço',
                'verbose_name_plural': 'Profissionais × serviços',
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('branch_id', models.UUIDField(blank=True, null=True, verbose_name='Unidade (UUID)')),
                ('rule_kind', models.CharField(choices=[('percent', 'Percentual'), ('fixed_cents', 'Valor fixo')], max_length=16, verbose_name='Tipo de regra')),
                ('percent_basis_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='Percentual (bps)')),
                ('fixed_cents', models.PositiveIntegerField(blank=True, null=True, verbose_name='Valor fixo')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='scheduling.professional', verbose_name='Profissional')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='scheduling.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Regra de comissão',
                'verbose_name_plural': 'Regras de comissão',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('starts_at', models.DateTimeField(verbose_name='Início')),
                ('ends_at', models.DateTimeField(verbose_name='Fim')),
                ('price_cents', models.BigIntegerField(default=0, verbose_name='Preço')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('no_show_pending', 'No-show pendente'), ('no_show', 'No-show'), ('checked_in', 'Check-in'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=32, verbose_name='Status')),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('portal', 'Portal'), ('walk_in', 'Walk-in'), ('admin', 'Admin')], default='admin', max_length=16, verbose_name='Origem')),
                ('explicit_confirmation', models.BooleanField(default=False, verbose_name='Confirmação explícita')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='master_data.customer', verbose_name='Cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='scheduling.professional', verbose_name='Profissional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='scheduling.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('starts_at', models.DateTimeField(verbose_name='Início')),
                ('ends_at', models.DateTimeField(verbose_name='Fim')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Motivo')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to='scheduling.professional', verbose_name='Profissional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Folga',
                'verbose_name_plural': 'Folgas',
            },
        ),
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['tenant', 'is_active'], name='scheduling__tenant__68435e_idx'),
        ),
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['tenant', 'provider'], name='scheduling__tenant__f1b5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarblock',
            index=models.Index(fields=['tenant', 'professional', 'starts_at', 'ends_at'], name='scheduling__tenant__0be54a_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarblock',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_scheduling_calendar_block_range'),
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['tenant', 'professional', 'weekday'], name='scheduling__tenant__bdb851_idx'),
        ),
        migrations.AddConstraint(
            model_name='businesshours',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='ck_scheduling_business_hours_weekday'),
        ),
        migrations.AddConstraint(
            model_name='businesshours',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_scheduling_business_hours_range'),
        ),
        migrations.AddIndex(
            model_name='recurringtimeoff',
            index=models.Index(fields=['tenant', 'professional', 'weekday'], name='scheduling__tenant__c0caf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringtimeoff',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='ck_scheduling_recurring_time_off_weekday'),
        ),
        migrations.AddConstraint(
            model_name='recurringtimeoff',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_scheduling_recurring_time_off_range'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', 'is_active'], name='scheduling__tenant__8d8787_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5), ('duration_minutes__lte', 480)), name='ck_scheduling_service_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents__gte', 0)), name='ck_scheduling_service_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='professionalservice',
            constraint=models.UniqueConstraint(fields=('tenant', 'professional', 'service'), name='uq_scheduling_professional_service'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['tenant', 'priority'], name='scheduling__tenant__e08168_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rule_kind', 'percent'), ('percent_basis_points__isnull', False), ('fixed_cents__isnull', True), ('percent_basis_points__lte', 10000)), models.Q(('rule_kind', 'fixed_cents'), ('fixed_cents__isnull', False), ('percent_basis_points__isnull', True)), _connector='OR'), name='ck_scheduling_commission_rule_kind'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'professional', 'starts_at'], name='scheduling__tenant__c3c02f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'status'], name='scheduling__tenant__ea90db_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_scheduling_appointment_range'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents__gte', 0)), name='ck_scheduling_appointment_price_nonneg'),
        ),
        migrations.AddIndex(
            model_name='timeoff',
            index=models.Index(fields=['tenant', 'professional', 'starts_at', 'ends_at'], name='scheduling__tenant__469656_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeoff',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_scheduling_time_off_range'),
        ),
    ]
