# Generated by Django 5.2.16 on 2026-07-29 01:52

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_electronic_proxy'),
        ('scheduling', '0002_appointment_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentFinancial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('service_price_cents', models.BigIntegerField(default=0, verbose_name='Preço do serviço')),
                ('deposit_paid_cents', models.BigIntegerField(default=0, verbose_name='Sinal pago')),
                ('discount_cents', models.BigIntegerField(default=0, verbose_name='Desconto')),
                ('discount_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Motivo do desconto')),
                ('balance_payment_method', models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('debit', 'Débito'), ('credit', 'Crédito'), ('other', 'Outro')], default='', max_length=16, verbose_name='Método do saldo')),
                ('deposit_recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='Sinal registrado em')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Liquidado em')),
            ],
            options={
                'verbose_name': 'Financeiro do agendamento',
                'verbose_name_plural': 'Financeiros dos agendamentos',
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('branch_id', models.UUIDField(blank=True, null=True, verbose_name='Unidade (UUID)')),
                ('base_amount_cents', models.BigIntegerField(verbose_name='Base')),
                ('commission_cents', models.BigIntegerField(verbose_name='Comissão')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('paid', 'Paga'), ('cancelled', 'Cancelada')], default='pending', max_length=16, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Lançamento de comissão',
                'verbose_name_plural': 'Lançamentos de comissão',
            },
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['tenant', 'is_active'], name='scheduling__tenant__a11d9b_idx'),
        ),
        migrations.AddField(
            model_name='appointmentfinancial',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='scheduling.appointment', verbose_name='Agendamento'),
        ),
        migrations.AddField(
            model_name='appointmentfinancial',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entry', to='scheduling.appointment', verbose_name='Agendamento'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='commission_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='scheduling.commissionrule', verbose_name='Regra'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_entries', to='scheduling.professional', verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_entries', to='scheduling.service', verbose_name='Serviço'),
        ),
        migrations.AddField(
            model_name='commissionentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='appointmentfinancial',
            constraint=models.CheckConstraint(condition=models.Q(('service_price_cents__gte', 0)), name='ck_scheduling_fin_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='appointmentfinancial',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_paid_cents__gte', 0)), name='ck_scheduling_fin_deposit_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='appointmentfinancial',
            constraint=models.CheckConstraint(condition=models.Q(('discount_cents__gte', 0)), name='ck_scheduling_fin_discount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='appointmentfinancial',
            constraint=models.CheckConstraint(condition=models.Q(('service_price_cents__gte', django.db.models.expressions.CombinedExpression(models.F('deposit_paid_cents'), '+', models.F('discount_cents')))), name='ck_scheduling_fin_deposit_discount_lte_price'),
        ),
        migrations.AddIndex(
            model_name='commissionentry',
            index=models.Index(fields=['tenant', 'professional', 'status'], name='scheduling__tenant__db6d90_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionentry',
            index=models.Index(fields=['tenant', 'created_at'], name='scheduling__tenant__b408f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionentry',
            constraint=models.UniqueConstraint(fields=('tenant', 'appointment'), name='uq_scheduling_commission_entry_appointment'),
        ),
        migrations.AddConstraint(
            model_name='commissionentry',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount_cents__gte', 0)), name='ck_scheduling_commission_base_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='commissionentry',
            constraint=models.CheckConstraint(condition=models.Q(('commission_cents__gte', 0)), name='ck_scheduling_commission_amount_nonneg'),
        ),
    ]
