# Generated by Django 5.2.16 on 2026-08-05 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_electronic_proxy'),
        ('master_data', '0007_nfe_greenfield_u2'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfeInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='Chave de idempotência')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('queued', 'Na fila'), ('submitting', 'Enviando'), ('polling', 'Consultando'), ('authorized', 'Autorizada'), ('rejected', 'Rejeitada'), ('failed', 'Falhou'), ('cancel_requested', 'Cancelamento pendente'), ('cancelled', 'Cancelada')], default='draft', max_length=32, verbose_name='Status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versão otimista')),
                ('nature_operation', models.CharField(default='VENDA', max_length=60, verbose_name='Natureza da operação')),
                ('finality', models.CharField(default='1', max_length=1, verbose_name='Finalidade')),
                ('consumer_final', models.BooleanField(default=False, verbose_name='Consumidor final')),
                ('buyer_presence', models.CharField(default='9', max_length=1, verbose_name='Presença comprador')),
                ('ind_ie_dest', models.CharField(default='9', max_length=1, verbose_name='indIEDest')),
                ('series', models.PositiveIntegerField(default=1, verbose_name='Série')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('tp_amb', models.CharField(default='2', max_length=1, verbose_name='Ambiente')),
                ('issue_date', models.DateField(verbose_name='Data de emissão')),
                ('freight_mod', models.CharField(default='9', max_length=1, verbose_name='Modalidade frete')),
                ('freight_cents', models.BigIntegerField(default=0, verbose_name='Frete (centavos)')),
                ('discount_cents', models.BigIntegerField(default=0, verbose_name='Desconto (centavos)')),
                ('payment_method', models.CharField(default='99', max_length=2, verbose_name='Forma pag. tPag')),
                ('payment_amount_cents', models.BigIntegerField(blank=True, null=True, verbose_name='Valor pag.')),
                ('total_cents', models.BigIntegerField(default=0, verbose_name='Total (centavos)')),
                ('fiscal_snapshot', models.JSONField(blank=True, null=True, verbose_name='Snapshot fiscal')),
                ('taxes_summary', models.JSONField(blank=True, null=True, verbose_name='Totais impostos')),
                ('access_key', models.CharField(blank=True, default='', max_length=44, verbose_name='Chave')),
                ('protocol', models.CharField(blank=True, default='', max_length=64, verbose_name='Protocolo')),
                ('rejection_code', models.CharField(blank=True, default='', max_length=16, verbose_name='cStat')),
                ('rejection_message', models.CharField(blank=True, default='', max_length=512, verbose_name='Motivo rejeição')),
                ('number_consumed', models.BooleanField(default=False, verbose_name='Número consumido')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, verbose_name='Correlação')),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash')),
                ('last_validation', models.JSONField(blank=True, null=True, verbose_name='Última validação')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_invoices', to='master_data.customer', verbose_name='Destinatário')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_invoices', to='master_data.provider', verbose_name='Emitente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'NF-e',
                'verbose_name_plural': 'NF-e',
            },
        ),
        migrations.CreateModel(
            name='NfeInvoiceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('actor', models.CharField(default='system', max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nfe.nfeinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_invoice_events', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Evento NF-e',
                'verbose_name_plural': 'Eventos NF-e',
                'ordering': ('occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='NfeNumberSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('series', models.PositiveIntegerField(default=1, verbose_name='Série')),
                ('tp_amb', models.CharField(choices=[('2', 'Homologação'), ('1', 'Produção')], default='2', max_length=1, verbose_name='Ambiente')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Próximo número')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_number_series', to='master_data.provider', verbose_name='Emitente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Série NF-e',
                'verbose_name_plural': 'Séries NF-e',
            },
        ),
        migrations.CreateModel(
            name='NfeProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=60, verbose_name='Código')),
                ('description', models.CharField(max_length=120, verbose_name='Descrição')),
                ('unit', models.CharField(default='UN', max_length=6, verbose_name='Unidade')),
                ('unit_price_cents', models.BigIntegerField(default=0, verbose_name='Preço unitário (centavos)')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('origin', models.CharField(default='0', max_length=1, verbose_name='Origem')),
                ('cfop_internal', models.CharField(default='5102', max_length=4, verbose_name='CFOP interno')),
                ('cfop_interstate', models.CharField(blank=True, default='6102', max_length=4, verbose_name='CFOP interestadual')),
                ('csosn', models.CharField(blank=True, default='', max_length=3, verbose_name='CSOSN')),
                ('icms_cst', models.CharField(blank=True, default='', max_length=3, verbose_name='CST ICMS')),
                ('icms_rate_bp', models.PositiveIntegerField(default=0, verbose_name='Alíquota ICMS (basis points, 1800=18%)')),
                ('pis_cst', models.CharField(default='07', max_length=2, verbose_name='CST PIS')),
                ('pis_rate_bp', models.PositiveIntegerField(default=0, verbose_name='Alíquota PIS bp')),
                ('cofins_cst', models.CharField(default='07', max_length=2, verbose_name='CST COFINS')),
                ('cofins_rate_bp', models.PositiveIntegerField(default=0, verbose_name='Alíquota COFINS bp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Produto fiscal NF-e',
                'verbose_name_plural': 'Produtos fiscais NF-e',
            },
        ),
        migrations.CreateModel(
            name='NfeInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(verbose_name='Item')),
                ('code', models.CharField(max_length=60, verbose_name='Código')),
                ('description', models.CharField(max_length=120, verbose_name='Descrição')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('cfop', models.CharField(max_length=4, verbose_name='CFOP')),
                ('unit', models.CharField(default='UN', max_length=6, verbose_name='Unidade')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantidade')),
                ('unit_price_cents', models.BigIntegerField(verbose_name='V. unitário (centavos)')),
                ('discount_cents', models.BigIntegerField(default=0, verbose_name='Desconto (centavos)')),
                ('total_cents', models.BigIntegerField(verbose_name='Total item (centavos)')),
                ('origin', models.CharField(default='0', max_length=1, verbose_name='Origem')),
                ('csosn', models.CharField(blank=True, default='', max_length=3, verbose_name='CSOSN')),
                ('icms_cst', models.CharField(blank=True, default='', max_length=3, verbose_name='CST ICMS')),
                ('taxes', models.JSONField(blank=True, default=dict, verbose_name='Impostos item')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nfe.nfeinvoice', verbose_name='NF-e')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nfe.nfeproduct', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item NF-e',
                'verbose_name_plural': 'Itens NF-e',
                'ordering': ('line_number',),
            },
        ),
        migrations.AddIndex(
            model_name='nfeinvoice',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='nfe_nfeinvo_tenant__798430_idx'),
        ),
        migrations.AddIndex(
            model_name='nfeinvoice',
            index=models.Index(fields=['tenant', 'access_key'], name='nfe_nfeinvo_tenant__072bba_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfeinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_nfe_invoice_tenant_idempotency'),
        ),
        migrations.AddIndex(
            model_name='nfeinvoiceevent',
            index=models.Index(fields=['invoice', 'occurred_at'], name='nfe_nfeinvo_invoice_28e898_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfenumberseries',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'series', 'tp_amb'), name='uq_nfe_series_provider_serie_amb'),
        ),
        migrations.AddConstraint(
            model_name='nfeproduct',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_nfe_product_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='nfeinvoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'line_number'), name='uq_nfe_item_invoice_line'),
        ),
    ]
