# Generated by Django 5.2.16 on 2026-09-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_product_st_ipi'),
        ('nfe', '0005_nfe_transmission_attempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nfeinutilization',
            new_name='nfe_nfeinut_tenant__a0eb40_idx',
            old_name='nfe_nfeinu_tenant__6a5b1e_idx',
        ),
        migrations.RenameIndex(
            model_name='nfeinutilization',
            new_name='nfe_nfeinut_tenant__637847_idx',
            old_name='nfe_nfeinu_tenant__f7c2a0_idx',
        ),
        migrations.RenameIndex(
            model_name='nfetransmissionattempt',
            new_name='nfe_nfetran_tenant__6457b3_idx',
            old_name='nfe_nfetran_tenant__7c3e21_idx',
        ),
        migrations.RenameIndex(
            model_name='nfetransmissionattempt',
            new_name='nfe_nfetran_tenant__6ded0e_idx',
            old_name='nfe_nfetran_tenant__a9b4f0_idx',
        ),
        migrations.AddField(
            model_name='nfeproduct',
            name='cest',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='nfeproduct',
            name='ip_enq',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='cEnq IPI'),
        ),
        migrations.AddField(
            model_name='nfeproduct',
            name='ipi_cst',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='CST IPI'),
        ),
        migrations.AddField(
            model_name='nfeproduct',
            name='ipi_rate_bp',
            field=models.PositiveIntegerField(default=0, verbose_name='Alíquota IPI bp'),
        ),
        migrations.AlterField(
            model_name='nfetransmissionattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='nfetransmissionattempt',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='nfetransmissionattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
