# Generated by Django 5.2.16 on 2026-09-07 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_product_st_ipi'),
        ('master_data', '0010_nbs_catalog'),
        ('nfe', '0007_nfe_product_gtin'),
        ('ops', '0007_rls_nf_artifact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NfeEntradaDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nsu', models.CharField(max_length=15, verbose_name='NSU')),
                ('schema_type', models.CharField(choices=[('resNFe', 'Resumo NF-e'), ('procNFe', 'NF-e processada'), ('resEvento', 'Resumo evento'), ('procEventoNFe', 'Evento processado'), ('other', 'Outro')], max_length=20, verbose_name='Tipo schema')),
                ('access_key', models.CharField(blank=True, default='', max_length=44, verbose_name='Chave')),
                ('issuer_cnpj', models.CharField(blank=True, default='', max_length=14, verbose_name='CNPJ emitente')),
                ('issuer_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Emitente')),
                ('recipient_cnpj', models.CharField(blank=True, default='', max_length=14, verbose_name='CNPJ destinatário')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('series', models.PositiveIntegerField(blank=True, null=True, verbose_name='Série')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data emissão')),
                ('total_cents', models.BigIntegerField(blank=True, null=True, verbose_name='Valor (centavos)')),
                ('nfe_status', models.CharField(blank=True, default='', max_length=32, verbose_name='Situação NF-e')),
                ('xml_status', models.CharField(choices=[('pending', 'XML pendente'), ('available', 'XML disponível'), ('error', 'Erro')], default='pending', max_length=16, verbose_name='Status XML')),
                ('manifest_status', models.CharField(choices=[('none', 'Sem manifestação'), ('ciencia', 'Ciência'), ('confirmada', 'Confirmada'), ('desconhecida', 'Desconhecida'), ('nao_realizada', 'Operação não realizada')], default='none', max_length=20, verbose_name='Manifestação')),
                ('xml_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash SHA-256')),
                ('raw_metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_entrada_documents', to='master_data.provider', verbose_name='Empresa destinatária')),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfe_entrada_documents', to='ops.storedfile', verbose_name='Arquivo XML')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'NF-e de entrada',
                'verbose_name_plural': 'NF-e de entrada',
            },
        ),
        migrations.CreateModel(
            name='NfeEntradaManifestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tp_evento', models.CharField(choices=[('210210', 'Ciência da Emissão'), ('210200', 'Confirmação da Operação'), ('210220', 'Desconhecimento'), ('210240', 'Operação não Realizada')], max_length=6, verbose_name='tpEvento')),
                ('n_seq', models.PositiveSmallIntegerField(default=1, verbose_name='nSeqEvento')),
                ('protocol', models.CharField(blank=True, default='', max_length=60, verbose_name='Protocolo')),
                ('c_stat', models.CharField(blank=True, default='', max_length=8, verbose_name='cStat')),
                ('x_motivo', models.CharField(blank=True, default='', max_length=512, verbose_name='xMotivo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Homologado'), ('rejected', 'Rejeitado')], default='pending', max_length=16, verbose_name='Status')),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, verbose_name='Correlação')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfe_entrada_manifestations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='nfe.nfeentradadocument', verbose_name='Documento')),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfe_entrada_manifestations', to='ops.storedfile', verbose_name='XML evento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Manifestação NF-e entrada',
                'verbose_name_plural': 'Manifestações NF-e entrada',
            },
        ),
        migrations.CreateModel(
            name='NfeDistribuicaoCursor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('ult_nsu', models.CharField(default='0', max_length=15, verbose_name='Último NSU')),
                ('max_nsu', models.CharField(default='0', max_length=15, verbose_name='Max NSU')),
                ('last_query_at', models.DateTimeField(blank=True, null=True, verbose_name='Última consulta')),
                ('last_c_stat', models.CharField(blank=True, default='', max_length=3, verbose_name='cStat')),
                ('last_x_motivo', models.TextField(blank=True, default='', verbose_name='xMotivo')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até')),
                ('automatic_enabled', models.BooleanField(default=False, verbose_name='Consulta automática')),
                ('interval_seconds', models.PositiveIntegerField(default=3600, verbose_name='Intervalo (s)')),
                ('tp_amb', models.CharField(choices=[('1', 'Produção'), ('2', 'Homologação')], default='2', max_length=1, verbose_name='Ambiente')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_distribuicao_cursor', to='master_data.provider', verbose_name='Empresa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Cursor distribuição NF-e',
                'verbose_name_plural': 'Cursors distribuição NF-e',
                'indexes': [models.Index(fields=['tenant', 'cnpj'], name='nfe_nfedist_tenant__a014d3_idx'), models.Index(fields=['tenant', 'automatic_enabled'], name='nfe_nfedist_tenant__1ff4da_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider'), name='uq_nfe_dist_cursor_tenant_provider')],
            },
        ),
        migrations.CreateModel(
            name='NfeDistribuicaoSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('ult_nsu_before', models.CharField(max_length=15, verbose_name='ultNSU antes')),
                ('ult_nsu_after', models.CharField(blank=True, default='', max_length=15, verbose_name='ultNSU depois')),
                ('max_nsu', models.CharField(blank=True, default='', max_length=15, verbose_name='maxNSU')),
                ('c_stat', models.CharField(blank=True, default='', max_length=3, verbose_name='cStat')),
                ('x_motivo', models.TextField(blank=True, default='', verbose_name='xMotivo')),
                ('documents_count', models.PositiveIntegerField(default=0, verbose_name='Documentos')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração ms')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, verbose_name='Correlação')),
                ('actor', models.CharField(default='system', max_length=64, verbose_name='Ator')),
                ('success', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Erro')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_distribuicao_sync_logs', to='master_data.provider', verbose_name='Empresa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Log sync distribuição NF-e',
                'verbose_name_plural': 'Logs sync distribuição NF-e',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'provider', '-created_at'], name='nfe_nfedist_tenant__b17d51_idx'), models.Index(fields=['tenant', 'correlation_id'], name='nfe_nfedist_tenant__f24c05_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='nfeentradadocument',
            index=models.Index(fields=['tenant', '-issue_date'], name='nfe_nfeentr_tenant__787e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='nfeentradadocument',
            index=models.Index(fields=['tenant', 'manifest_status'], name='nfe_nfeentr_tenant__ae1d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='nfeentradadocument',
            index=models.Index(fields=['tenant', 'xml_status'], name='nfe_nfeentr_tenant__80b598_idx'),
        ),
        migrations.AddIndex(
            model_name='nfeentradadocument',
            index=models.Index(fields=['tenant', 'issuer_cnpj'], name='nfe_nfeentr_tenant__16b6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='nfeentradadocument',
            index=models.Index(fields=['tenant', 'access_key'], name='nfe_nfeentr_tenant__01bcc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfeentradadocument',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'nsu'), name='uq_nfe_entrada_tenant_provider_nsu'),
        ),
        migrations.AddConstraint(
            model_name='nfeentradadocument',
            constraint=models.UniqueConstraint(condition=models.Q(('access_key__gt', '')), fields=('tenant', 'access_key'), name='uq_nfe_entrada_tenant_access_key'),
        ),
        migrations.AddIndex(
            model_name='nfeentradamanifestation',
            index=models.Index(fields=['tenant', 'document'], name='nfe_nfeentr_tenant__20b314_idx'),
        ),
        migrations.AddIndex(
            model_name='nfeentradamanifestation',
            index=models.Index(fields=['tenant', '-created_at'], name='nfe_nfeentr_tenant__9c231e_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfeentradamanifestation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('tenant', 'document', 'tp_evento', 'n_seq'), name='uq_nfe_entrada_manifest_accepted'),
        ),
    ]
