# Generated by Django 5.2.16 on 2026-07-19 17:32

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_tenant_roles'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_guia', models.CharField(choices=[('DAS', 'DAS'), ('DARF', 'DARF')], max_length=8)),
                ('competencia', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Use AAAA-MM')])),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('valor_principal'), '+', models.F('valor_multa')), '+', models.F('valor_juros')), output_field=models.DecimalField(decimal_places=2, max_digits=14))),
                ('linha_digitavel', models.TextField(blank=True, default='')),
                ('pix_copia_cola', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('DISPONIVEL', 'Disponível'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('RETIFICADO', 'Retificado'), ('VENCIDO', 'Vencido'), ('EM_CONTESTACAO', 'Em contestação')], default='PROCESSANDO', max_length=32)),
                ('compliance_status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('bloqueado', 'Bloqueado'), ('dispensado', 'Dispensado')], default='pendente', max_length=16)),
                ('compliance_motivo', models.TextField(blank=True, default='')),
                ('pdf_storage_key', models.TextField(blank=True, default='')),
                ('versao_atual', models.PositiveIntegerField(default=1)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_fiscais', to='master_data.provider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'competencia', 'status'], name='das_guiafis_tenant__f4970e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_guia_fiscal_tenant_idempotency'), models.UniqueConstraint(fields=('tenant', 'provider', 'tipo_guia', 'competencia', 'versao_atual'), name='uq_guia_fiscal_natural_key'), models.CheckConstraint(condition=models.Q(('valor_principal__gte', 0), ('valor_multa__gte', 0), ('valor_juros__gte', 0)), name='ck_guia_fiscal_valores_nao_negativos'), models.CheckConstraint(condition=models.Q(('versao_atual__gte', 1)), name='ck_guia_fiscal_versao_min')],
            },
        ),
    ]
