# Generated by Django 5.2.16 on 2026-07-19 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0001_initial'),
        ('ops', '0004_rls_app_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiafiscal',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_fiscais', to='ops.storedfile'),
        ),
    ]
