# Generated by Django 5.2.16 on 2026-07-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0002_guia_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiafiscal',
            options={'verbose_name': 'Guia fiscal', 'verbose_name_plural': 'Guias fiscais'},
        ),
    ]
