# Generated by Django 5.2.16 on 2026-07-20 00:36

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_field_verbose_names_pt'),
        ('das', '0003_portuguese_verbose_names'),
        ('master_data', '0004_field_verbose_names_pt'),
        ('ops', '0006_field_verbose_names_pt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiafiscal',
            name='competencia',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Use AAAA-MM')], verbose_name='Competência'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='compliance_motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo compliance'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='compliance_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('bloqueado', 'Bloqueado'), ('dispensado', 'Dispensado')], default='pendente', max_length=16, verbose_name='Status de compliance'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='idempotency_key',
            field=models.CharField(max_length=128, verbose_name='Chave de idempotência'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='linha_digitavel',
            field=models.TextField(blank=True, default='', verbose_name='Linha digitável'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_fiscais', to='ops.storedfile', verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='pdf_storage_key',
            field=models.TextField(blank=True, default='', verbose_name='Chave storage PDF'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='pix_copia_cola',
            field=models.TextField(blank=True, default='', verbose_name='PIX copia e cola'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_fiscais', to='master_data.provider', verbose_name='Prestador'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='status',
            field=models.CharField(choices=[('PROCESSANDO', 'Processando'), ('DISPONIVEL', 'Disponível'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('RETIFICADO', 'Retificado'), ('VENCIDO', 'Vencido'), ('EM_CONTESTACAO', 'Em contestação')], default='PROCESSANDO', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='tipo_guia',
            field=models.CharField(choices=[('DAS', 'DAS'), ('DARF', 'DARF')], max_length=8, verbose_name='Tipo de guia'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='valor_juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor juros'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor multa'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='valor_principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor principal'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='valor_total',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('valor_principal'), '+', models.F('valor_multa')), '+', models.F('valor_juros')), output_field=models.DecimalField(decimal_places=2, max_digits=14), verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='guiafiscal',
            name='versao_atual',
            field=models.PositiveIntegerField(default=1, verbose_name='Versão'),
        ),
    ]
