# Generated by Django 5.2.16 on 2026-07-19 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_tenant_roles'),
        ('fiscal', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_tax', 'Pending tax'), ('queued', 'Queued'), ('submitting', 'Submitting'), ('polling', 'Polling'), ('authorized', 'Authorized'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('ibge_code', models.CharField(max_length=7)),
                ('competence_date', models.DateField()),
                ('amount_cents', models.BigIntegerField()),
                ('resolved_params', models.JSONField(blank=True, null=True)),
                ('internal_payload', models.JSONField(blank=True, null=True)),
                ('focus_status_raw', models.JSONField(blank=True, null=True)),
                ('focus_ref', models.CharField(blank=True, default='', max_length=128)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('rejection_code', models.CharField(blank=True, default='', max_length=64)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_issues', to='master_data.customer')),
                ('fiscal_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nf_issues', to='fiscal.fiscalprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_issues', to='master_data.provider')),
                ('resolved_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fiscal.municipaltaxrule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_issues', to='master_data.servicecatalogitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalRuleSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_rule_id', models.UUIDField(blank=True, null=True)),
                ('catalog_version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
                ('nf_issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule_snapshot', to='issuance.nfissue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NfIssueEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('actor', models.CharField(default='system', max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('nf_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='issuance.nfissue')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_issue_events', to='accounts.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='nfissue',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='issuance_nf_tenant__607ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='nfissue',
            index=models.Index(fields=['tenant', 'competence_date'], name='issuance_nf_tenant__b6f6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='nfissue',
            index=models.Index(fields=['tenant', 'correlation_id'], name='issuance_nf_tenant__58b450_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfissue',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_nf_issue_tenant_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='nfissue',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='ck_nf_issue_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='nfissueevent',
            index=models.Index(fields=['nf_issue', 'occurred_at'], name='issuance_nf_nf_issu_2698bb_idx'),
        ),
    ]
