# Generated by Django 5.2.16 on 2026-07-19 23:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_certificate_gates'),
        ('issuance', '0001_initial'),
        ('ops', '0004_rls_app_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('xml', 'XML'), ('pdf', 'PDF')], max_length=8)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('nf_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='issuance.nfissue')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_artifacts', to='ops.storedfile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nf_issue', 'kind'), name='uq_nf_artifact_issue_kind')],
            },
        ),
    ]
