# Generated by Django 5.2.16 on 2026-07-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuance', '0002_nf_artifact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalrulesnapshot',
            options={'verbose_name': 'Snapshot da regra fiscal', 'verbose_name_plural': 'Snapshots da regra fiscal'},
        ),
        migrations.AlterModelOptions(
            name='nfartifact',
            options={'verbose_name': 'Artefato NFS-e', 'verbose_name_plural': 'Artefatos NFS-e'},
        ),
        migrations.AlterModelOptions(
            name='nfissue',
            options={'verbose_name': 'Emissão NFS-e', 'verbose_name_plural': 'Emissões NFS-e'},
        ),
        migrations.AlterModelOptions(
            name='nfissueevent',
            options={'verbose_name': 'Evento de emissão', 'verbose_name_plural': 'Eventos de emissão'},
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending_tax', 'Imposto pendente'), ('queued', 'Na fila'), ('submitting', 'Enviando'), ('polling', 'Consultando'), ('authorized', 'Autorizada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada'), ('failed', 'Falhou')], default='draft', max_length=32),
        ),
    ]
