# Generated by Django 5.2.16 on 2026-07-20 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_field_verbose_names_pt'),
        ('fiscal', '0003_field_verbose_names_pt'),
        ('issuance', '0003_portuguese_verbose_names'),
        ('master_data', '0004_field_verbose_names_pt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfissueevent',
            options={'ordering': ('occurred_at',), 'verbose_name': 'Evento de emissão', 'verbose_name_plural': 'Eventos de emissão'},
        ),
        migrations.AlterField(
            model_name='fiscalrulesnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='fiscalrulesnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='fiscalrulesnapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='nfartifact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='nfartifact',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='nfartifact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='amount_cents',
            field=models.BigIntegerField(verbose_name='Valor (centavos)'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='competence_date',
            field=models.DateField(verbose_name='Data de competência'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='correlation_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='ID de correlação'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_issues', to='master_data.customer', verbose_name='Tomador'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='fiscal_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nf_issues', to='fiscal.fiscalprofile', verbose_name='Perfil fiscal'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='focus_ref',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Referência Focus'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='focus_status_raw',
            field=models.JSONField(blank=True, null=True, verbose_name='Status bruto Focus'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='ibge_code',
            field=models.CharField(max_length=7, verbose_name='Código IBGE'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='idempotency_key',
            field=models.CharField(max_length=128, verbose_name='Chave de idempotência'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='internal_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload interno'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='payload_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Hash do payload'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_issues', to='master_data.provider', verbose_name='Prestador'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='rejection_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Código de rejeição'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='resolved_params',
            field=models.JSONField(blank=True, null=True, verbose_name='Parâmetros resolvidos'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='resolved_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fiscal.municipaltaxrule', verbose_name='Regra resolvida'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_issues', to='master_data.servicecatalogitem', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending_tax', 'Imposto pendente'), ('queued', 'Na fila'), ('submitting', 'Enviando'), ('polling', 'Consultando'), ('authorized', 'Autorizada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada'), ('failed', 'Falhou')], default='draft', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='nfissueevent',
            name='actor',
            field=models.CharField(default='system', max_length=64, verbose_name='Ator'),
        ),
        migrations.AlterField(
            model_name='nfissueevent',
            name='from_status',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Status de origem'),
        ),
        migrations.AlterField(
            model_name='nfissueevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Metadados'),
        ),
        migrations.AlterField(
            model_name='nfissueevent',
            name='nf_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='issuance.nfissue', verbose_name='Emissão NFS-e'),
        ),
        migrations.AlterField(
            model_name='nfissueevent',
            name='occurred_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ocorrido em'),
        ),
        migrations.AlterField(
            model_name='nfissueevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nf_issue_events', to='accounts.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='nfissueevent',
            name='to_status',
            field=models.CharField(max_length=32, verbose_name='Status de destino'),
        ),
    ]
