# Generated by Django 5.2.16 on 2026-07-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuance', '0004_field_verbose_names_pt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfissue',
            name='amount_cents',
            field=models.BigIntegerField(verbose_name='Valor'),
        ),
    ]
