# Generated by Django 5.2.16 on 2026-07-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuance', '0005_d12_cosmetic_index_verbose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfissue',
            name='focus_ref',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Referência Provedor Exeq'),
        ),
        migrations.AlterField(
            model_name='nfissue',
            name='focus_status_raw',
            field=models.JSONField(blank=True, null=True, verbose_name='Status bruto Provedor Exeq'),
        ),
    ]
